name: "Run Tests"

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    name: Run GUT Tests
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v2
        with:
          version: 4.3.0 # Using 4.3.0 as a stable target for "4.6" dev branch
      
      - name: Install GUT (since it is ignored by git)
        run: |
          mkdir -p Hafnium/addons/gut
          git clone --depth 1 https://github.com/bitwes/Gut.git target_dir
          mv target_dir/addons/gut Hafnium/addons/
          rm -rf target_dir
      
      - name: Import Resources
        run: godot --headless --path Hafnium/ --import --quit

      - name: Run GUT Tests
        run: |
          godot --headless --path Hafnium/ -s addons/gut/gut_cmdln.gd -gdir=res://tests/unit -gexit
